import type { LanguageOption } from "./types/LanguageOption";

// create list of langauges
const languageArray : LanguageOption[] =[
    { label: "Abkhaz", value: "ab" },
    { label: "Acehnese", value: "ace" },
    { label: "Acholi", value: "ach" },
    { label: "Afrikaans", value: "af" },
    { label: "Albanian", value: "sq" },
    { label: "Alur", value: "alz" },
    { label: "Amharic", value: "am" },
    { label: "Arabic", value: "ar" },
    { label: "Armenian", value: "hy" },
    { label: "Assamese", value: "as" },
    { label: "Awadhi", value: "awa" },
    { label: "Aymara", value: "ay" },
    { label: "Azerbaijani", value: "az" },
    { label: "Balinese", value: "ban" },
    { label: "Bambara", value: "bm" },
    { label: "Bashkir", value: "ba" },
    { label: "Basque", value: "eu" },
    { label: "Batak Karo", value: "btx" },
    { label: "Batak Simalungun", value: "bts" },
    { label: "Batak Toba", value: "bbc" },
    { label: "Belarusian", value: "be" },
    { label: "Bemba", value: "bem" },
    { label: "Bengali", value: "bn" },
    { label: "Betawi", value: "bew" },
    { label: "Bhojpuri", value: "bho" },
    { label: "Bikol", value: "bik" },
    { label: "Bosnian", value: "bs" },
    { label: "Breton", value: "br" },
    { label: "Bulgarian", value: "bg" },
    { label: "Buryat", value: "bua" },
    { label: "Cantonese", value: "yue" },
    { label: "Catalan", value: "ca" },
    { label: "Cebuano", value: "ceb" },
    { label: "Chichewa (Nyanja)", value: "ny" },
    { label: "Chinese (Simplified)", value: "zh-CN" },
    { label: "Chinese (Traditional)", value: "zh-TW" },
    { label: "Chuvash", value: "cv" },
    { label: "Corsican", value: "co" },
    { label: "Crimean Tatar", value: "crh" },
    { label: "Croatian", value: "hr" },
    { label: "Czech", value: "cs" },
    { label: "Danish", value: "da" },
    { label: "Dutch", value: "nl" },
    { label: "English", value: "en" },
    { label: "French", value: "fr" },
    { label: "French (Canada)", value: "fr-CA" },
    { label: "French (France)", value: "fr-FR" },
    { label: "German", value: "de" },
    { label: "Greek", value: "el" },
    { label: "Hindi", value: "hi" },
    { label: "Italian", value: "it" },
    { label: "Japanese", value: "ja" },
    { label: "Korean", value: "ko" },
    { label: "Portuguese (Brazil)", value: "pt-BR" },
    { label: "Portuguese (Portugal)", value: "pt-PT" },
    { label: "Russian", value: "ru" },
    { label: "Spanish", value: "es" },
    { label: "Swedish", value: "sv" },
    { label: "Turkish", value: "tr" },
    { label: "Ukrainian", value: "uk" },
    { label: "Vietnamese", value: "vi" },
    { label: "Zulu", value: "zu" },
];

export default languageArray;